# example/pubspec.yaml
name: flutter_element_example
environment:
  sdk: "^3.6.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_element:
    path: ../
  get: ^4.6.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
