# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build and deploy to tencent cos

on:
  push:
    branches: ["main"]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache-key: flutter-3.6.0-stable-${{ hashFiles('**/pubspec.lock') }}
          cache: true

      # - name: Cache pub dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       example/.dart_tool
      #       example/.pub-cache
      #       example/.pub
      #       example/build
      #     key: ${{ runner.os }}-pub-${{ hashFiles('example/pubspec.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pub-

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install coscmd
        run: |
          python -m pip install --upgrade pip
          pip install coscmd

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ vars.TENCENT_SECRET_ID }}
          SECRET_KEY: ${{ vars.TENCENT_SECRET_KEY }}
          BUCKET: ${{ vars.TENCENT_BUCKETNAME }}
          REGION: ap-guangzhou
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Install dependencies
        run: |
          cd example
          flutter pub get --no-example

      - name: Build web
        run: |
          cd example
          flutter build web --release

      - name: Clean bucket
        run: |
          coscmd delete -r / --force

      - name: Upload to COS
        run: |
          coscmd upload -r example/build/web/ /
