# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build and deploy to tencent cos

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install coscmd
        run: sudo pip install coscmd

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          BUCKET: ${{ secrets.TENCENT_BUCKETNAME }}
          REGION: ap-guangzhou
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Install dependencies
        run: |
          cd example
          flutter pub get

      - name: Build web
        run: |
          cd example
          flutter build web

      - name: Clean bucket
        run: |
          coscmd delete -r / --force

      - name: Upload to COS
        run: |
          coscmd upload -r example/build/web/ /
